name: 'Download Google Drive file'
description: 'Donwloads a file from Google Drive using service account credentials'
inputs:
  token:
    description: 'Google access token'
    required: true
  file-id:
    description: 'ID of the file in Google Drive'
  file-url:
    description: 'URL to the share link for the file on Google Drive'
  folder-id: 
    description: 'ID of the folder in Google Drive'
  folder-url: 
    description: "Shareable URL for the folder on Google Drive"
  path:
    description: 'Path at which the file will be saved'
    required: true

runs:
  using: node20
  main: dist/index.js
  post: dist/index.js
